title: QWorld QWHACK 2021
nav_title: QWHack2021 Hack<span class="hide-very-narrow">athon</span><br><small><span class="hide-very-narrow">with</span> QWorld</small>

event_date: 27–30 November 2021
registration_opens_date: 17 November 2021
registration_closes_date: 25 November 2021

author: QWorld
mailbox_address: https://qworld.net/

description:
  The event aimed to bring together people who are interested in developing quantum programming and want to meet this
  field through project-based learning. The hackathon was attended by those who know quantum programming,
  but also people interested in the subject and wanted willing to learn this subject from teammates.

url: "https://qworld-hack-test.github.io/"
github_repo: qworld-hack-test

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - registration.md
  - agenda.md
  - projects.md
  - videos-slides.md
  - resources.md
  - about.md

# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: demo

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: demo

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
